//
// Code generated by https://ella.to, DO NOT EDIT.
//

// Enums

export enum AuthType {
  SUCCEED = "SUCCEED",
  FAILED = "FAILED",
}

// Messages

export interface RequestAuthCodeArgs {
  email: string;
}

export interface RequestAuthCodeReturns {
  token: string;
}

// Services

export interface SessionService {
  RequestAuthCode: (
    args: RequestAuthCodeArgs,
    headers?: Object
  ) => Promise<RequestAuthCodeReturns>;
}

// Clients

// Helper Functions
